FIND_LIBRARY(CLN cln)
FIND_PATH(CLN_FOUND cln/cln.h )
IF ( CLN AND CLN_FOUND )
  MESSAGE("-- Looking for CLN - found")
  SET( CLN_INCLUDE "${CLN_FOUND}")
  SET( CLN_LIBS "${CLN}")
  MESSAGE( "-- Ginac includes ${CLN_INCLUDE}")
  MESSAGE( "-- Ginac libs     ${CLN_LIBS}")
ELSE ( CLN AND CLN_FOUND )
  MESSAGE(FATAL_ERROR "Looking for CLN - not found")
ENDIF ( CLN AND CLN_FOUND )
